criterion:
  classes_per_batch: 17
  supervised_epochs: 100
  supervised_imgs_per_class: 6
  supervised_views: 1
  temperature: 0.1
  unsupervised_batch_size: 64
data:
  color_jitter_strength: 1.0
  dataset: ROV
  image_folder: imagenet_full_size/061417/
  label_smoothing: 0.0
  normalize: true
  root_path: /root/datasets/all_crops/
  subset_path: ROV_subsets
  unique_classes_per_rank: false
  unlabeled_frac: 0.9
logging:
  folder: /root/suncet/path_to_save_models_and_logs_i2map/
  write_tag: suncet-tmp
meta:
  copy_data: true
  device: cuda:0
  load_checkpoint: false
  model_name: resnet50
  output_dim: 2048
  read_checkpoint: null
  use_fp16: true
  use_pred_head: false
optimization:
  epochs: 200
  final_lr: 0.0012
  lr: 1.2
  momentum: 0.9
  nesterov: false
  start_lr: 0.3
  warmup: 10
  weight_decay: 1.0e-06
